/*
* Author: Hao-Xin Wang<wanghaoxin1996@gmail.com>
* Creation Date: 2025-02-21
*
*/

#ifndef QLPEPS_ALGORITHM_VMC_UPDATE_WAVE_FUNCTION_COMPONENT_CLASSES_WAVE_FUNCTION_COMPONENT_ALL_H
#define QLPEPS_ALGORITHM_VMC_UPDATE_WAVE_FUNCTION_COMPONENT_CLASSES_WAVE_FUNCTION_COMPONENT_ALL_H

#include "qlpeps/vmc_basic/wave_function_component.h" // TPSWaveFunctionComponent

namespace qlpeps {
/**
 * Base class for different Monte-Carlo sweep update strategies.
 * The derived class can serve as the template parameter MCSweepUpdater in VMC executor and MC measurement executor.
 */
template<typename WaveFunctionDress = qlpeps::NoDress>
class MonteCarloSweepUpdaterBase {
 public:
  /**
   * @brief Default constructor initializes the random number generator using `std::random_device`.
   * 
   * On Linux, `std::random_device` is expected to produce non-deterministic random numbers.
   * In an MPI environment, random number generated by std::random_device in different process
   * is also expected to be independent.
   */
  MonteCarloSweepUpdaterBase() : random_engine_(std::random_device{}()) {}

  /**
   * @brief Constructor with explicit seed for reproducible Monte Carlo sampling.
   * 
   * Useful for regression testing and debugging where deterministic behavior is required.
   * 
   * @param seed The seed value for the random number generator.
   */
  explicit MonteCarloSweepUpdaterBase(unsigned int seed) : random_engine_(seed) {}

  ///< The following member function should be defined in derived class to define the MC sweep strategies.
  template<typename TenElemT, typename QNT>
  void operator()(const SplitIndexTPS<TenElemT, QNT> &sitps,
                  TPSWaveFunctionComponent<TenElemT, QNT, WaveFunctionDress> &tps_component,
                  std::vector<double> &accept_rates) {}
 protected:
  std::uniform_real_distribution<double> u_double_ = std::uniform_real_distribution<double>(0, 1.0);
  std::mt19937 random_engine_;
};
}//qlpeps

#include "square_nn_updater.h"
#include "square_3site_updater.h"
#include "square_hubbard_u1u1_updater.h"

#endif //QLPEPS_ALGORITHM_VMC_UPDATE_WAVE_FUNCTION_COMPONENT_CLASSES_WAVE_FUNCTION_COMPONENT_ALL_H
